source_letter:  # $TASK_NAME
   decoder_type: transformer
   dict: C:\Users\USER\Documents\Naim\S2S\training\ctc\dataset\data_root\source_letter\dict.txt
   data: C:\Users\USER\Documents\Naim\S2S\training\ctc\dataset\data_root\source_letter
   encoder_layer: 6
   loss_weight: 8.0
target_letter:
   decoder_type: transformer
   dict: C:\Users\USER\Documents\Naim\S2S\training\ctc\dataset\data_root\target_letter\dict.txt
   data: C:\Users\USER\Documents\Naim\S2S\training\ctc\dataset\data_root\target_letter
   encoder_layer: 8
   loss_weight: 8.0
decoder_target_ctc:
   decoder_type: ctc
   dict: C:\Users\USER\Documents\Naim\S2S\training\ctc\dataset\data_root\decoder_target_ctc\dict.txt
   data: C:\Users\USER\Documents\Naim\S2S\training\ctc\dataset\data_root\decoder_target_ctc
   decoder_layer: 3
   loss_weight: 1.6